<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Serial transport provider for OpenDeviceStudio.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OpenDeviceStudio.Abstractions/OpenDeviceStudio.Abstractions.csproj" />
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>
</Project>
