<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Generic Host integration, lifecycle, DI and module system for UpperHost.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UpperHost.Abstractions/UpperHost.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>
</Project>
