<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Protocol codecs and request/response or streaming protocol runtimes for OpenDeviceStudio.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OpenDeviceStudio.Abstractions/OpenDeviceStudio.Abstractions.csproj" />
  </ItemGroup>
</Project>
