<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Safe JSON key/value and Apache Arrow Canonical RawData file-system storage providers for UpperHost.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UpperHost.Abstractions/UpperHost.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Apache.Arrow" />
  </ItemGroup>
</Project>
