<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/UpperHost.Abstractions/UpperHost.Abstractions.csproj" />
    <ProjectReference Include="../../src/UpperHost.Hosting/UpperHost.Hosting.csproj" />
    <ProjectReference Include="../../src/UpperHost.Starters/UpperHost.Starters.csproj" />
    <ProjectReference Include="../../src/UpperHost.Control/UpperHost.Control.csproj" />
    <ProjectReference Include="../../src/UpperHost.StateMachines/UpperHost.StateMachines.csproj" />
    <ProjectReference Include="../../src/UpperHost.Workflows/UpperHost.Workflows.csproj" />
  </ItemGroup>
</Project>
