<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Composable workflow runtime for device application processes.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OpenDeviceStudio.Abstractions/OpenDeviceStudio.Abstractions.csproj" />
    <ProjectReference Include="../OpenDeviceStudio.Control/OpenDeviceStudio.Control.csproj" />
  </ItemGroup>
</Project>
