<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>UpperHost.Sample.SerialTcpReference</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/UpperHost.Abstractions/UpperHost.Abstractions.csproj" />
    <ProjectReference Include="../../src/UpperHost.Protocols/UpperHost.Protocols.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>
</Project>
