<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Serial transport provider for UpperHost.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UpperHost.Abstractions/UpperHost.Abstractions.csproj" />
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>
</Project>
