<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <AssemblyName>UpperHost.App</AssemblyName>
    <RootNamespace>UpperHost.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/UpperHost.Starters/UpperHost.Starters.csproj" />
    <ProjectReference Include="../../src/UpperHost.Presentation.Wpf/UpperHost.Presentation.Wpf.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
